{
    "train-data-paths": [
        "/mnt/ssd-cluster/P3/hellaswag_Topic_without_the_ending_answer/train_text_document",
        "/mnt/ssd-cluster/P3/adversarial_qa_droberta_answer_the_following_q/train_text_document",
        "/mnt/ssd-cluster/P3/quoref_Answer_Question_Given_Context/train_text_document",
        "/mnt/ssd-cluster/P3/anli_must_be_true_r3_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/anli_does_this_imply_r3_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/ag_news_classify/train_text_document",
        "/mnt/ssd-cluster/P3/race_middle_Is_this_the_right_answer/train_text_document",
        "/mnt/ssd-cluster/P3/quoref_Find_Answer/train_text_document",
        "/mnt/ssd-cluster/P3/cos_e_v1.11_question_description_option_text/train_text_document",
        "/mnt/ssd-cluster/P3/anli_guaranteed_true_r2/train_text_document",
        "/mnt/ssd-cluster/P3/cnn_dailymail_3.0.0_news_card_view/train_text_document",
        "/mnt/ssd-cluster/P3/trec_fine_grained_HUM_context_first/train_text_document",
        "/mnt/ssd-cluster/P3/paws_labeled_final_task_description_no_label/train_text_document",
        "/mnt/ssd-cluster/P3/anli_consider_always_sometimes_never_r3_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/web_questions_short_general_knowledge_q/train_text_document",
        "/mnt/ssd-cluster/P3/wiki_hop_original_choose_best_object_interrogative_1/train_text_document",
        "/mnt/ssd-cluster/P3/hellaswag_complete_first_then_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/cnn_dailymail_3.0.0_sum_in_brief/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_wsc.fixed_Who_or_what_is_are/train_text_document",
        "/mnt/ssd-cluster/P3/multi_news_summarize/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_multirc_correct/train_text_document",
        "/mnt/ssd-cluster/P3/cnn_dailymail_3.0.0_write_an_outline/train_text_document",
        "/mnt/ssd-cluster/P3/anli_does_this_imply_r1_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_cb_justified_in_saying/train_text_document",
        "/mnt/ssd-cluster/P3/quartz_use_info_from_paragraph_question/train_text_document",
        "/mnt/ssd-cluster/P3/anli_guaranteed_true_r3_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/common_gen_choice_in_concept_centric_sentence_generation/train_text_document",
        "/mnt/ssd-cluster/P3/hellaswag_complete_first_then/train_text_document",
        "/mnt/ssd-cluster/P3/cos_e_v1.11_question_option_description_id/train_text_document",
        "/mnt/ssd-cluster/P3/quoref_Context_Contains_Answer/train_text_document",
        "/mnt/ssd-cluster/P3/duorc_SelfRC_extract_answer/train_text_document",
        "/mnt/ssd-cluster/P3/duorc_ParaphraseRC_movie_director/train_text_document",
        "/mnt/ssd-cluster/P3/anli_guaranteed_possible_impossible_r1_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_cb_can_we_infer/train_text_document",
        "/mnt/ssd-cluster/P3/wiki_bio_what_content/train_text_document",
        "/mnt/ssd-cluster/P3/quarel_heres_a_story/train_text_document",
        "/mnt/ssd-cluster/P3/paws_labeled_final_Rewrite/train_text_document",
        "/mnt/ssd-cluster/P3/wiqa_what_is_the_final_step_of_the_following_process/train_text_document",
        "/mnt/ssd-cluster/P3/cnn_dailymail_3.0.0_2_or_3_sentences/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_rte_must_be_true_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/adversarial_qa_dbert_based_on/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_wic_similar_sense_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/piqa_pick_correct_choice_index/train_text_document",
        "/mnt/ssd-cluster/P3/ropes_prompt_bottom_no_hint/train_text_document",
        "/mnt/ssd-cluster/P3/anli_claim_true_false_inconclusive_r1_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/wiki_hop_original_generate_object/train_text_document",
        "/mnt/ssd-cluster/P3/anli_guaranteed_possible_impossible_r2_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_rte_guaranteed_true_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_copa_cause_effect_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/anli_always_sometimes_never_r1/train_text_document",
        "/mnt/ssd-cluster/P3/trec_pick_the_best_descriptor/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_cb_does_this_imply_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_rte_does_it_follow_that/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_copa_plausible_alternatives_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/ropes_prompt_beginning/train_text_document",
    ],
    "test-data-paths": [
        "/mnt/ssd-cluster/P3/amazon_polarity_convey_negative_or_positive_sentiment/test_text_document",
        "/mnt/ssd-cluster/P3/anli_does_this_imply_r3_score_eval/test_text_document",
    ],
    "valid-data-paths": [
        "/mnt/ssd-cluster/P3/wiki_hop_original_choose_best_object_affirmative_2/validation_text_document",
        "/mnt/ssd-cluster/P3/duorc_SelfRC_decide_worth_it/validation_text_document",
        "/mnt/ssd-cluster/P3/gigaword_in_a_nutshell/validation_text_document",
        "/mnt/ssd-cluster/P3/glue_mrpc_equivalent/validation_text_document",
    ],
    "vocab-file": "/mnt/ssd-1/data/20B_tokenizer.json",
    "merge-file": null,
    "save": "/mnt/ssd-cluster/small0/",
    "load": "/mnt/ssd-cluster/small0/",
    "tensorboard-dir": "/mnt/ssd-1/tensorboard",
    "log-dir": "/mnt/ssd-1/logs",
    "wandb_team": "eleutherai"
}
