{
    "train-data-paths": [
        "/mnt/ssd-cluster/P3/hellaswag_Topic_without_the_ending_answer/train_text_document",
    ],
    "test-data-paths": [
        "/mnt/ssd-cluster/P3/anli_does_this_imply_r3_score_eval/test_text_document",
    ],
    "valid-data-paths": [
        "/mnt/ssd-cluster/P3/wiki_hop_original_choose_best_object_affirmative_2/validation_text_document",
    ],
    "vocab-file": "/mnt/ssd-1/data/20B_tokenizer.json",
    "merge-file": null,
    "save": "/mnt/ssd-cluster/small0/",
    "load": "/mnt/ssd-cluster/small0/",
    "tensorboard-dir": "/mnt/ssd-1/tensorboard",
    "log-dir": "/mnt/ssd-1/logs",
    "wandb_team": "eleutherai"
}
