{
    "train-data-paths": [
        "/mnt/ssd-cluster/P3/hellaswag_Topic_without_the_ending_answer/train_text_document",
        "/mnt/ssd-cluster/P3/adversarial_qa_droberta_answer_the_following_q/train_text_document",
        "/mnt/ssd-cluster/P3/quoref_Answer_Question_Given_Context/train_text_document",
        "/mnt/ssd-cluster/P3/anli_must_be_true_r3_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/anli_does_this_imply_r3_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/ag_news_classify/train_text_document",
        "/mnt/ssd-cluster/P3/race_middle_Is_this_the_right_answer/train_text_document",
        "/mnt/ssd-cluster/P3/quoref_Find_Answer/train_text_document",
        "/mnt/ssd-cluster/P3/qasc_qa_with_separated_facts_1/train_text_document",
        "/mnt/ssd-cluster/P3/winogrande_winogrande_debiased_does_underscore_refer_to_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/anli_take_the_following_as_truth_r2/train_text_document",
        "/mnt/ssd-cluster/P3/cosmos_qa_description_context_question_answer_text/train_text_document",
        "/mnt/ssd-cluster/P3/anli_guaranteed_true_r3/train_text_document",
        "/mnt/ssd-cluster/P3/duorc_SelfRC_answer_question/train_text_document",
        "/mnt/ssd-cluster/P3/trec_fine_grained_LOC_context_first/train_text_document",
        "/mnt/ssd-cluster/P3/cos_e_v1.11_question_description_option_text/train_text_document",
        "/mnt/ssd-cluster/P3/anli_guaranteed_true_r2/train_text_document",
        "/mnt/ssd-cluster/P3/cnn_dailymail_3.0.0_news_card_view/train_text_document",
        "/mnt/ssd-cluster/P3/trec_fine_grained_HUM_context_first/train_text_document",
        "/mnt/ssd-cluster/P3/anli_MNLI_crowdsource_r3_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_wsc.fixed_the_pronoun_refers_to/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_multirc_confirm/train_text_document",
        "/mnt/ssd-cluster/P3/duorc_ParaphraseRC_decide_worth_it/train_text_document",
        "/mnt/ssd-cluster/P3/quail_context_question_answer_description_text/train_text_document",
        "/mnt/ssd-cluster/P3/adversarial_qa_dbert_tell_what_it_is/train_text_document",
        "/mnt/ssd-cluster/P3/wiki_hop_original_choose_best_object_interrogative_2/train_text_document",
        "/mnt/ssd-cluster/P3/anli_MNLI_crowdsource_r3/train_text_document",
        "/mnt/ssd-cluster/P3/piqa_Correct_the_solution_if_false_from_sol_1/train_text_document",
        "/mnt/ssd-cluster/P3/paws_labeled_final_task_description_no_label/train_text_document",
        "/mnt/ssd-cluster/P3/anli_consider_always_sometimes_never_r3_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/web_questions_short_general_knowledge_q/train_text_document",
        "/mnt/ssd-cluster/P3/wiki_hop_original_choose_best_object_interrogative_1/train_text_document",
        "/mnt/ssd-cluster/P3/hellaswag_complete_first_then_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/cnn_dailymail_3.0.0_sum_in_brief/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_wsc.fixed_Who_or_what_is_are/train_text_document",
        "/mnt/ssd-cluster/P3/multi_news_summarize/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_multirc_correct/train_text_document",
        "/mnt/ssd-cluster/P3/cnn_dailymail_3.0.0_write_an_outline/train_text_document",
        "/mnt/ssd-cluster/P3/piqa_Correct_the_solution_if_false_from_sol_2/train_text_document",
        "/mnt/ssd-cluster/P3/piqa_what_is_the_correct_ending/train_text_document",
        "/mnt/ssd-cluster/P3/anli_take_the_following_as_truth_r3_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/quartz_use_info_from_question_paragraph/train_text_document",
        "/mnt/ssd-cluster/P3/winogrande_winogrande_xl_underscore_refer_to/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_cb_take_the_following_as_truth_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_wic_question_context_meaning/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_wic_affirmation_true_or_false/train_text_document",
        "/mnt/ssd-cluster/P3/anli_does_this_imply_r1_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_cb_justified_in_saying/train_text_document",
        "/mnt/ssd-cluster/P3/quartz_use_info_from_paragraph_question/train_text_document",
        "/mnt/ssd-cluster/P3/anli_guaranteed_true_r3_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/common_gen_choice_in_concept_centric_sentence_generation/train_text_document",
        "/mnt/ssd-cluster/P3/hellaswag_complete_first_then/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_wic_question_context_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_multirc_is_a_correct_answer_/train_text_document",
        "/mnt/ssd-cluster/P3/social_i_qa_Generate_answer/train_text_document",
        "/mnt/ssd-cluster/P3/cos_e_v1.11_question_option_description_id/train_text_document",
        "/mnt/ssd-cluster/P3/quoref_Context_Contains_Answer/train_text_document",
        "/mnt/ssd-cluster/P3/duorc_SelfRC_extract_answer/train_text_document",
        "/mnt/ssd-cluster/P3/duorc_ParaphraseRC_movie_director/train_text_document",
        "/mnt/ssd-cluster/P3/anli_guaranteed_possible_impossible_r1_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_cb_can_we_infer/train_text_document",
        "/mnt/ssd-cluster/P3/wiki_bio_what_content/train_text_document",
        "/mnt/ssd-cluster/P3/quarel_heres_a_story/train_text_document",
        "/mnt/ssd-cluster/P3/ag_news_which_section_choices/train_text_document",
        "/mnt/ssd-cluster/P3/anli_guaranteed_true_r1/train_text_document",
        "/mnt/ssd-cluster/P3/anli_does_it_follow_that_r3_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/squad_v2_Questions_with_Context_Without_Prompt_Keywords_unanswerable/train_text_document",
        "/mnt/ssd-cluster/P3/ai2_arc_ARC_Challenge_qa_options/train_text_document",
        "/mnt/ssd-cluster/P3/paws_labeled_final_Rewrite/train_text_document",
        "/mnt/ssd-cluster/P3/wiqa_what_is_the_final_step_of_the_following_process/train_text_document",
        "/mnt/ssd-cluster/P3/cnn_dailymail_3.0.0_2_or_3_sentences/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_rte_must_be_true_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/adversarial_qa_dbert_based_on/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_wic_similar_sense_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/piqa_pick_correct_choice_index/train_text_document",
        "/mnt/ssd-cluster/P3/anli_consider_always_sometimes_never_r1_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/common_gen_Example_prompt/train_text_document",
        "/mnt/ssd-cluster/P3/hellaswag_Randomized_prompts_template/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_multirc_paragraph_question_is_it_/train_text_document",
        "/mnt/ssd-cluster/P3/duorc_SelfRC_generate_question/train_text_document",
        "/mnt/ssd-cluster/P3/paws_labeled_final_Rewrite_no_label/train_text_document",
        "/mnt/ssd-cluster/P3/glue_qqp_quora/train_text_document",
        "/mnt/ssd-cluster/P3/hellaswag_Open_ended_completion/train_text_document",
        "/mnt/ssd-cluster/P3/ropes_background_new_situation_answer/train_text_document",
        "/mnt/ssd-cluster/P3/ropes_prompt_bottom_no_hint/train_text_document",
        "/mnt/ssd-cluster/P3/anli_claim_true_false_inconclusive_r1_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/wiki_hop_original_generate_object/train_text_document",
        "/mnt/ssd-cluster/P3/anli_guaranteed_possible_impossible_r2_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_rte_guaranteed_true_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_copa_cause_effect_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/anli_always_sometimes_never_r1/train_text_document",
        "/mnt/ssd-cluster/P3/trec_pick_the_best_descriptor/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_cb_does_this_imply_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/anli_always_sometimes_never_r1_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/adversarial_qa_droberta_generate_question/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_copa_choose_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/wiki_hop_original_choose_best_object_affirmative_3/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_record_exercise/train_text_document",
        "/mnt/ssd-cluster/P3/ag_news_classify_question_first/train_text_document",
        "/mnt/ssd-cluster/P3/anli_always_sometimes_never_r2/train_text_document",
        "/mnt/ssd-cluster/P3/anli_should_assume_r3/train_text_document",
        "/mnt/ssd-cluster/P3/ropes_read_background_situation/train_text_document",
        "/mnt/ssd-cluster/P3/anli_can_we_infer_r1/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_record_choose_between/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_copa__What_could_happen_next_C1_or_C2__score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_copa_choose/train_text_document",
        "/mnt/ssd-cluster/P3/anli_take_the_following_as_truth_r1_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/social_i_qa_Show_choices_and_generate_answer/train_text_document",
        "/mnt/ssd-cluster/P3/winogrande_winogrande_debiased_Replace/train_text_document",
        "/mnt/ssd-cluster/P3/wiki_qa_Topic_Prediction_Question_and_Answer_Pair/train_text_document",
        "/mnt/ssd-cluster/P3/race_middle_Select_the_best_answer/train_text_document",
        "/mnt/ssd-cluster/P3/duorc_SelfRC_question_answering/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_cb_always_sometimes_never_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/dbpedia_14_pick_one_category_for_the_following_text/train_text_document",
        "/mnt/ssd-cluster/P3/race_high_Select_the_best_answer_generate_span_/train_text_document",
        "/mnt/ssd-cluster/P3/sciq_Multiple_Choice_Question_First/train_text_document",
        "/mnt/ssd-cluster/P3/wiki_bio_who/train_text_document",
        "/mnt/ssd-cluster/P3/piqa_choose_the_most_appropriate_solution/train_text_document",
        "/mnt/ssd-cluster/P3/qasc_is_correct_2/train_text_document",
        "/mnt/ssd-cluster/P3/anli_GPT_3_style_r1/train_text_document",
        "/mnt/ssd-cluster/P3/adversarial_qa_droberta_tell_what_it_is/train_text_document",
        "/mnt/ssd-cluster/P3/paws_labeled_final_context_question/train_text_document",
        "/mnt/ssd-cluster/P3/anli_claim_true_false_inconclusive_r3_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/ag_news_classify_with_choices/train_text_document",
        "/mnt/ssd-cluster/P3/quoref_Answer_Test/train_text_document",
        "/mnt/ssd-cluster/P3/duorc_SelfRC_title_generation/train_text_document",
        "/mnt/ssd-cluster/P3/anli_take_the_following_as_truth_r2_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_cb_guaranteed_possible_impossible/train_text_document",
        "/mnt/ssd-cluster/P3/quail_no_prompt_id/train_text_document",
        "/mnt/ssd-cluster/P3/anli_justified_in_saying_r1/train_text_document",
        "/mnt/ssd-cluster/P3/paws_labeled_final_Meaning/train_text_document",
        "/mnt/ssd-cluster/P3/wiki_qa_Generate_Question_from_Topic/train_text_document",
        "/mnt/ssd-cluster/P3/anli_must_be_true_r3/train_text_document",
        "/mnt/ssd-cluster/P3/qasc_qa_with_separated_facts_2/train_text_document",
        "/mnt/ssd-cluster/P3/anli_claim_true_false_inconclusive_r2_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/sciq_Direct_Question/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_copa_more_likely/train_text_document",
        "/mnt/ssd-cluster/P3/imdb_Reviewer_Enjoyment_Yes_No/train_text_document",
        "/mnt/ssd-cluster/P3/multi_news_summary_scenario/train_text_document",
        "/mnt/ssd-cluster/P3/anli_always_sometimes_never_r3_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/amazon_polarity_flattering_or_not/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_rte_does_it_follow_that/train_text_document",
        "/mnt/ssd-cluster/P3/super_glue_copa_plausible_alternatives_score_eval/train_text_document",
        "/mnt/ssd-cluster/P3/ropes_prompt_beginning/train_text_document",
    ],
    "test-data-paths": [
        "/mnt/ssd-cluster/P3/amazon_polarity_convey_negative_or_positive_sentiment/test_text_document",
        "/mnt/ssd-cluster/P3/anli_must_be_true_r3_score_eval/test_text_document",
        "/mnt/ssd-cluster/P3/anli_does_this_imply_r3_score_eval/test_text_document",
    ],
    "valid-data-paths": [
        "/mnt/ssd-cluster/P3/wiki_hop_original_choose_best_object_affirmative_2/validation_text_document",
        "/mnt/ssd-cluster/P3/duorc_SelfRC_decide_worth_it/validation_text_document",
        "/mnt/ssd-cluster/P3/gigaword_in_a_nutshell/validation_text_document",
        "/mnt/ssd-cluster/P3/glue_mrpc_equivalent/validation_text_document",
        "/mnt/ssd-cluster/P3/anli_guaranteed_possible_impossible_r3_score_eval/validation_text_document",
        "/mnt/ssd-cluster/P3/xsum_college_roommate_asked_DOC_so_I_recap/validation_text_document",
        "/mnt/ssd-cluster/P3/winogrande_winogrande_xl_underscore_refer_to_score_eval/validation_text_document",
        "/mnt/ssd-cluster/P3/super_glue_wic_similar_sense/validation_text_document",
        "/mnt/ssd-cluster/P3/multi_news_distill/validation_text_document",
    ],
    "vocab-file": "/mnt/ssd-1/data/20B_tokenizer.json",
    "merge-file": null,
    "save": "/mnt/ssd-cluster/small0/",
    "load": "/mnt/ssd-cluster/small0/",
    "tensorboard-dir": "/mnt/ssd-1/tensorboard",
    "log-dir": "/mnt/ssd-1/logs",
    "wandb_team": "eleutherai"
}
