# Data paths and options when using EleutherAI cluster
{
  "data-path": "/mnt/ssd-1/data/pile/pile_text_document",
  # or for weighted datasets: 
  # "train-data-paths": ["/mnt/ssd-cluster/data/enron/enron_text_document", "/mnt/ssd-cluster/data/enron/enron_text_document"],
  # "test-data-paths": ["/mnt/ssd-cluster/data/enron/enron_text_document", "/mnt/ssd-cluster/data/enron/enron_text_document"],
  # "valid-data-paths": ["/mnt/ssd-cluster/data/enron/enron_text_document", "/mnt/ssd-cluster/data/enron/enron_text_document"],
  # "train-data-weights": [1., 2.],
  # "test-data-weights": [2., 1.],
  # "valid-data-weights": [0.5, 0.4],
  "finetune": True,
  "vocab-file": "/mnt/ssd-1/data/gpt2-vocab.json",
  "merge-file": "/mnt/ssd-1/data/gpt2-merges.txt",
  "save": "checkpoints/good-loss/1-1-1",
  #"tensorboard-dir": "tensorboard",
  #"load": "checkpoints/1-1-1",
  "load_teacher": "/mnt/ssd-1/neox_checkpoints/dense_medium_checkpoints/global_step25000",
  "use_wandb": True,
  "wandb_host": "https://api.wandb.ai",
  "checkpoint_validation_with_forward_pass": False,
  "log-dir": "logs",
  "wandb_team": "eleutherai",
  "wandb_project": "gali"
}
