# Suggested data paths when using GPT-NeoX locally
{
  "data-path": "/workspace/enron/enron_text_document",
  "vocab-file": "/workspace/gpt2-vocab.json",
  "merge-file": "/workspace/gpt2-merges.txt",
  "_save": "checkpoints",
  "_load": "checkpoints",
  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
}
